[workspace]
members = [
    "crates/frostmirror-core",
    "crates/frostmirror-fetch",
    "crates/frostmirror-import",
    "crates/frostmirror-serve",
    "crates/frostmirror",
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pillisan42/frostmirror"
keywords = ["local","mirror","airgap","panamax","romt"]
categories = ["accessibility"]

[workspace.dependencies]
# Internal crates
frostmirror-core = { path = "crates/frostmirror-core" }
frostmirror-fetch = { path = "crates/frostmirror-fetch" }
frostmirror-import = { path = "crates/frostmirror-import" }
frostmirror-serve = { path = "crates/frostmirror-serve" }

# Async runtime
tokio = { version = "1.52.1", features = ["full"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.2"

# HTTP
reqwest = { version = "0.13.3", features = ["rustls", "stream"], default-features = false }
axum = { version = "0.8.9", features = ["macros"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["fs", "cors", "trace"] }

# Compression
brotli = "8.0.2"

# Hashing
sha2 = "0.11.0"
hex = "0.4"

# CLI
clap = { version = "4.6.1", features = ["derive", "env"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1"
thiserror = "2.0.18"

# File watching
notify = "8.2.0"

# Semver
semver = { version = "1.0.28", features = ["serde"] }

# Misc
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3"
walkdir = "2"
rust-embed = { version = "8", features = ["axum"] }
mime_guess = "2"
futures = "0.3"
