use anyhow::{Context, Result};
use frostmirror_core::bundle::{sha256_hex, BundleBuilder, SectionKind};
use frostmirror_core::manifest::{BundleType, Manifest};
use std::path::{Path, PathBuf};

/// Builds a self-contained `.pkg` snapshot of a running frostmirror instance
/// (mirror tree + optional config files), suitable for redeployment on
/// another server via the existing `import` flow.
pub struct Exporter {
    mirror_dir: PathBuf,
    config_dir: Option<PathBuf>,
}

impl Exporter {
    pub fn new(mirror_dir: PathBuf) -> Self {
        Self {
            mirror_dir,
            config_dir: None,
        }
    }

    /// Include `frostmirror.toml` and `depends.toml` from the given config
    /// directory in the snapshot.
    pub fn with_config_dir(mut self, config_dir: PathBuf) -> Self {
        self.config_dir = Some(config_dir);
        self
    }

    pub fn export(&self, output: &Path) -> Result<ExportResult> {
        if !self.mirror_dir.exists() {
            anyhow::bail!("mirror directory does not exist: {}", self.mirror_dir.display());
        }

        // Seed the manifest with targets/toolchain from the existing one if
        // present; otherwise use sensible defaults. Snapshots are always Full.
        let (targets, toolchain) = read_existing_manifest_meta(&self.mirror_dir);
        let mut manifest = Manifest::new(BundleType::Full, None, targets, toolchain);
        let mut builder = BundleBuilder::new();

        let mut crate_count = 0usize;
        let mut rustup_count = 0usize;
        let mut dist_count = 0usize;
        let mut index_count = 0usize;

        // 1. Crates: mirror/crates/{name}/{version}/download
        let crates_dir = self.mirror_dir.join("crates");
        if crates_dir.exists() {
            for entry in walkdir::WalkDir::new(&crates_dir) {
                let entry = entry?;
                if !entry.file_type().is_file() {
                    continue;
                }
                let rel = entry
                    .path()
                    .strip_prefix(&self.mirror_dir)
                    .expect("walk under mirror_dir");
                // Expect crates/<name>/<version>/download
                let parts: Vec<_> = rel.components().collect();
                if parts.len() != 4 {
                    continue;
                }
                let name = parts[1].as_os_str().to_string_lossy().to_string();
                let version = parts[2].as_os_str().to_string_lossy().to_string();
                let filename = parts[3].as_os_str().to_string_lossy();
                if filename != "download" {
                    continue;
                }
                let data = std::fs::read(entry.path())
                    .with_context(|| format!("failed to read crate {}", entry.path().display()))?;
                let sha = sha256_hex(&data);
                let size = data.len() as u64;
                manifest.add_crate(name.clone(), version.clone(), sha, size);
                builder.add_crate_file(&name, &version, data);
                crate_count += 1;
            }
        }

        // 2. Index entries: mirror/index/* (skip generated config.json)
        let index_dir = self.mirror_dir.join("index");
        if index_dir.exists() {
            for entry in walkdir::WalkDir::new(&index_dir) {
                let entry = entry?;
                if !entry.file_type().is_file() {
                    continue;
                }
                let rel = entry
                    .path()
                    .strip_prefix(&self.mirror_dir)
                    .expect("walk under mirror_dir");
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                if rel_str == "index/config.json" {
                    continue; // regenerated by importer
                }
                let data = std::fs::read(entry.path())
                    .with_context(|| format!("failed to read index {}", entry.path().display()))?;
                builder.add_section(SectionKind::Index, rel_str, data);
                index_count += 1;
            }
        }

        // 3. Rustup binaries: mirror/rustup/dist/{target}/{filename}
        let rustup_dir = self.mirror_dir.join("rustup").join("dist");
        if rustup_dir.exists() {
            for entry in walkdir::WalkDir::new(&rustup_dir) {
                let entry = entry?;
                if !entry.file_type().is_file() {
                    continue;
                }
                let rel = entry
                    .path()
                    .strip_prefix(&rustup_dir)
                    .expect("walk under rustup_dir");
                let parts: Vec<_> = rel.components().collect();
                if parts.len() != 2 {
                    continue;
                }
                let target = parts[0].as_os_str().to_string_lossy().to_string();
                let filename = parts[1].as_os_str().to_string_lossy().to_string();
                let data = std::fs::read(entry.path())
                    .with_context(|| format!("failed to read rustup {}", entry.path().display()))?;
                let sha = sha256_hex(&data);
                let size = data.len() as u64;
                manifest.add_rustup(target.clone(), filename.clone(), sha, size);
                builder.add_rustup_file(&target, &filename, data);
                rustup_count += 1;
            }
        }

        // 4. Toolchain dist: mirror/dist/**
        let dist_dir = self.mirror_dir.join("dist");
        if dist_dir.exists() {
            for entry in walkdir::WalkDir::new(&dist_dir) {
                let entry = entry?;
                if !entry.file_type().is_file() {
                    continue;
                }
                let rel = entry
                    .path()
                    .strip_prefix(&dist_dir)
                    .expect("walk under dist_dir");
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                let data = std::fs::read(entry.path())
                    .with_context(|| format!("failed to read dist {}", entry.path().display()))?;
                let sha = sha256_hex(&data);
                let size = data.len() as u64;
                manifest.add_dist(rel_str.clone(), sha, size);
                builder.add_dist_file(&rel_str, data);
                dist_count += 1;
            }
        }

        // 5. Optional config files
        if let Some(config_dir) = &self.config_dir {
            for filename in ["frostmirror.toml", "depends.toml"] {
                let path = config_dir.join(filename);
                if path.exists() {
                    let data = std::fs::read(&path)
                        .with_context(|| format!("failed to read {}", path.display()))?;
                    builder.add_config_file(filename, data);
                }
            }
        }

        manifest.seal();
        builder
            .add_manifest(&manifest)
            .context("failed to add manifest to bundle")?;

        if let Some(parent) = output.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        builder
            .write_to_file(output)
            .with_context(|| format!("failed to write snapshot to {}", output.display()))?;

        let total_size = std::fs::metadata(output)?.len();

        Ok(ExportResult {
            output_path: output.to_path_buf(),
            crate_count,
            rustup_count,
            dist_count,
            index_count,
            total_size,
        })
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ExportResult {
    pub output_path: PathBuf,
    pub crate_count: usize,
    pub rustup_count: usize,
    pub dist_count: usize,
    pub index_count: usize,
    pub total_size: u64,
}

fn read_existing_manifest_meta(mirror_dir: &Path) -> (Vec<String>, String) {
    let manifest_path = mirror_dir.join("manifest.json");
    if let Ok(content) = std::fs::read_to_string(&manifest_path) {
        if let Ok(m) = serde_json::from_str::<Manifest>(&content) {
            return (m.targets, m.toolchain);
        }
    }
    (
        vec!["x86_64-unknown-linux-gnu".to_string()],
        "stable".to_string(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Importer;

    fn write(path: &Path, data: &[u8]) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, data).unwrap();
    }

    /// Populate a fake mirror tree with one crate, an index entry, a rustup
    /// binary, a dist file, and config files, then export, then import into a
    /// fresh dir and assert all artifacts round-tripped.
    #[test]
    fn export_then_import_round_trips() {
        let src = tempfile::tempdir().unwrap();
        let mirror = src.path().join("mirror");
        let config = src.path().join("config");

        // 1 crate
        write(
            &mirror.join("crates/serde/1.0.0/download"),
            b"fake serde 1.0.0 bytes",
        );
        // 1 index entry
        write(
            &mirror.join("index/se/rd/serde"),
            b"{\"name\":\"serde\",\"vers\":\"1.0.0\"}\n",
        );
        // 1 rustup binary
        write(
            &mirror.join("rustup/dist/x86_64-unknown-linux-gnu/rustup-init"),
            b"\x7fELF rustup",
        );
        // 1 dist file
        write(
            &mirror.join("dist/channel-rust-stable.toml"),
            b"date = \"2026-01-01\"\n",
        );
        // 2 config files
        write(&config.join("frostmirror.toml"), b"base_url = \"x\"");
        write(&config.join("depends.toml"), b"[dependencies]\n");

        // Export
        let snapshot = src.path().join("snapshot.pkg");
        let result = Exporter::new(mirror.clone())
            .with_config_dir(config.clone())
            .export(&snapshot)
            .unwrap();
        assert_eq!(result.crate_count, 1);
        assert_eq!(result.rustup_count, 1);
        assert_eq!(result.dist_count, 1);
        assert_eq!(result.index_count, 1);
        assert!(snapshot.exists());

        // Import into a fresh location
        let dest = tempfile::tempdir().unwrap();
        let dest_mirror = dest.path().join("mirror");
        let dest_config = dest.path().join("config");
        std::fs::create_dir_all(&dest_mirror).unwrap();
        let importer = Importer::new(dest_mirror.clone()).with_config_dir(dest_config.clone());
        importer.import(&snapshot).unwrap();

        // Assert artifacts present
        assert_eq!(
            std::fs::read(dest_mirror.join("crates/serde/1.0.0/download")).unwrap(),
            b"fake serde 1.0.0 bytes"
        );
        assert!(dest_mirror.join("index/se/rd/serde").exists());
        assert!(dest_mirror
            .join("rustup/dist/x86_64-unknown-linux-gnu/rustup-init")
            .exists());
        assert!(dest_mirror.join("dist/channel-rust-stable.toml").exists());
        assert_eq!(
            std::fs::read(dest_config.join("frostmirror.toml")).unwrap(),
            b"base_url = \"x\""
        );
        assert_eq!(
            std::fs::read(dest_config.join("depends.toml")).unwrap(),
            b"[dependencies]\n"
        );
    }
}
